name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup go toolchain
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      
      - name: build app
        run: ./scripts/build.sh